Add bmi metadata
katmratliff/avulsion-bmi pull request #11
Opened 2018-07-09 19:57 UTC by mcflugen

This pull request updates the RAFEM BMI, and makes RAFEM work with Python 2 and 3.

Some highlights:
* Use the `six` package to make RAFEM work with both Python 2 and Python 3. There wasn't much to do for this. I think the biggest things were use `range` and `zip` from `six.moves`.
* Update the BMI. Added `get_var_location` and `get_var_itemsize`, and an optional `out` keyword to `get_value`, `get_grid_shape`, `get_grid_spacing`, and `get_grid_origin`.
* Minor updates to the pymt metadata (stuff inside the `.bmi` folder)
* Added lines to `setup.py` so that RAFEM is installed as a `pymt` plugin.
* Create an empty `output_data/river_info.out` file when RAFEM is initialized.

I don't think any of these things should change how RAFEM runs, only it's interface to `pymt`.

2018-07-10 01:39 UTC, katmratliff commented on rafem/rivermodule.py
> +            with open("output_data/river_info.out", "w"):
can we move this to run_model.py?

2018-07-10 18:27 UTC, katmratliff requested changes

2018-07-10 18:27 UTC, katmratliff commented on .bmi/input.yaml.tmpl
> +dt_day: 0.1           # timestep (days)
changed the default timestep to 0.1 days

2018-07-10 18:27 UTC, katmratliff commented on rafem/rivermodule.py
> +                pass
How about deleting ll. 172-176 and using this suggested change in the coupling script? 
https://github.com/mcflugen/rafem_cem_coupling/pull/1

2018-07-11 22:18 UTC, mcflugen commented on .bmi/input.yaml.tmpl
> +dt_day: 0.1           # timestep (days)
The `dt_day` variable is now able to be specified by the user. The default is 0.1 days.

2018-07-11 22:26 UTC, mcflugen commented on rafem/rivermodule.py
> +                pass
All of the output for the `RiverModule` should be handled by the `RiverModule` class. If the above code were to be moved to the coupling script, it wouldn't be obvious to another user that they would need to first create a file called `output_data/river_info.out`.

As a compromise, I've changed this so that the user can specify the names of the `RiverModule` output files through `saveavulsions`, `savecourseupdates`, and `save_splay_deposit` keywords in the input file. Values for these keys are either `False` (to indicate no output for that parameters) or the name of a file.

As an example, the `input.yaml` file could contain the following:
```yaml
saveavulsions: False # flag for saving avulsion info
savecourseupdates: output_data/river_info.out # flag for saving course updates
save_splay_deposit: False
```

2018-07-12 01:14 UTC, merged

2018-07-12 01:14 UTC, katmratliff commented
Looks good! Thanks, Eric!